version: '3.7'
services:
  todo_list:
    build: .
    image: todo_list
    ports:
      - 8080:8080
    environment:
      DATABASE_URL_WRITE: postgres://postgres:example@host.docker.internal/example_db
      DATABASE_URL_READ: postgres://postgres:example@host.docker.internal/example_db
      PORT: 8080
