version: '3.7'
services:
  postgresql:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    image: example_db
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
