[package]
name = "actix-web-basic"
version = "0.1.0"
authors = ["Sho Yoshida"]
edition = "2018"

[dependencies]
actix-web = "3.0.2"
actix-files = "0.5.0"
time = "0.2.26"
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[dev-dependencies]
actix-rt = "2.2.0"
